server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "fahad123"

    # -----------------------------
    # SOURCES CONFIG (IMPORTANT)
    # -----------------------------
    sources:
      youtube: false
      soundcloud: true
      bandcamp: true
      twitch: false
      vimeo: false
      http: true
      local: false

    # -----------------------------
    # AUDIO FILTERS (optional but recommended)
    # -----------------------------
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      rotation: true
      distortion: true
      channelMix: true
      lowPass: true

    # -----------------------------
    # FRAME HANDLING
    # -----------------------------
    frameBufferDurationMs: 5000

    opusEncodingQuality: 10

    resamplingQuality: LOW

    trackStuckThresholdMs: 10000
    useSeekGhosting: true

    # -----------------------------
    # PLAYER BEHAVIOR
    # -----------------------------
    youtubePlaylistLoadLimit: 0

    playerUpdateInterval: 5

logging:
  level:
    root: INFO
    lavalink: INFO